Repository opensearch-project/remote-vector-index-builder, pull requests merged in 2025-03, with the labels that each got.

#8 Create API.md
  API.md
Labels: documentation

#18 Modified index build data types and expected values to match API contract
  API.md
  remote_vector_index_builder/core/common/models/index_build_parameters.py
  remote_vector_index_builder/core/common/models/vectors_dataset.py
  remote_vector_index_builder/core/tasks.py
  test_remote_vector_index_builder/test_core/common/models/test_vectors_dataset.py
  test_remote_vector_index_builder/test_core/test_tasks.py
Labels: documentation, enhancement

#25 Adding ef_search to index_build_parameters
  remote_vector_index_builder/core/common/models/index_build_parameters.py
Labels: bug
